### ISSUE TITLE
hi! is there any paper link?

### ISSUE THREAD

**Issue by tqlblzj** [Tejas-Deo/Safe-Navigation-Training-Autonomous-Vehicles-using-Deep-Reinforcement-Learning-in-CARLA#2]

**Comment by Tejas-Deo** [comment]
Sorry for the delay. But I have added the paper link in the repo. Thanks!

**Comment by Tejas-Deo** [comment]
Sorry for the delay. But I have added the paper link in the repo. Thanks!
Closing the issue
