### ISSUE TITLE
AttributeError: 'CarEnv' object has no attribute 'camera_spawn_point'

### ISSUE THREAD

**Issue by wolf212121j** [Tejas-Deo/Safe-Navigation-Training-Autonomous-Vehicles-using-Deep-Reinforcement-Learning-in-CARLA#7]
When l try to run driving_dqn.py , l met tis problem:   
 self.collision_sensor = self.world.spawn_actor(col_sensor, self.camera_spawn_point, attach_to = self.vehicle)
AttributeError: 'CarEnv' object has no attribute 'camera_spawn_point'

**Comment by Tejas-Deo** [comment]
Please uncomment the code above it from line 208 to get ride of the Attribute error as the variable is defined the in the commented code. 

Closing the thread
